# Generated by Django 4.2.7 on 2024-02-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_movieitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movieitem',
            table='Movieitem',
        ),
    ]
