# Generated by Django 4.2.7 on 2024-02-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_movieitem_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieitem',
            old_name='cart',
            new_name='film',
        ),
        migrations.RenameField(
            model_name='movieitem',
            old_name='product',
            new_name='movie',
        ),
    ]
